### PR TITLE
[BUGFIX] File props empty

### PR DESCRIPTION
**Pull request by stafast**
Added conditions to get properties from FAL

### CODE REVIEW

**Comment by lukaszuznanski** [comment]
How can I reproduce this error? I add images to my content elements and meta data is properly rendered without this patch

**Comment by stafast** [comment]
For example with „File collection“ and Type: folder.
Use CE uploads for output your file collection

**Comment by lukaszuznanski** [comment]
I created File collection with 2 files with custom title and description, then I used CE uploads to output this collection and I can see properly rendered title and description without patch. Are you sure you are using tag 2.0.0 or dev-master? Maybe I'm missing something? Which TYPO3 version you are using?

**Comment by stafast** [comment]
„...with 2 files with custom title and description...“ Not there, directly in the files properties in filelist.
(Get properties from tbl:sys_file_metadata and not tbl:sys_file_reference)

**Comment by lukaszuznanski** [comment]
Ok. Thank you. That's correct, there is a bug and your patch fixes it. Looks good for me.

**Pull request merged**
