### PR TITLE
[FEATURE] Add felogin integration

### LINKED ISSUE #119: [FEATURE] Using felogin authentication over headless API
Not sure if this is possible already out of the box, can you as developer say something to this? If it's not possible, this would be a good feature-resquest as the user management is one of the strength of TYPO3 over other systems in my opinion, which should work especially in web-apps.

### PR DESCRIPTION
**Pull request by lukaszuznanski**
Resolves #119 
- check code
- add missing label translations

### CODE REVIEW

**Comment by Moongazer** [comment]
I've tested the feature by setup a Vue client with login form, and its working great so far. A tiny problem was the returning HTML code inside the JSON response from the original `Logout.html` template, so it would be great if you can add the following to your code:

New file `Templates/Login/Logout.html`:
```
<f:spaceless>
    <f:format.raw>
        <f:format.json value="{
            form: {
                title: '{f:translate(key:\'logout\')}',
                action: '{f:uri.action(action:\'login\')}',
                method: 'POST',
                fields: '{f:render(partial: \'LogoutFields\', arguments: \'{_all}\') -> headless:format.json.decode()-> headless:loginForm(action:\'login\', name:\'field\') -> headless:format.json.decode()}'
            },
            message: {
                header: '{f:render(partial: \'RenderLabelOrMessage\', arguments: \'{key: \\\'status_header\\\'}\')}',
                message: '{f:render(partial: \'RenderLabelOrMessage\', arguments: \'{key: \\\'status_message\\\'}\')}: {f:translate(key:\'username\')} {user.username}'
            },
            recovery: '{f:render(partial: \'Recovery\', arguments: \'{_all}\') -> headless:format.json.decode()}',
            flashMessages: '{f:render(partial: \'FlashMessages\', arguments: \'{_all}\') -> headless:format.json.decode()}'
        }"/>
    </f:format.raw>
</f:spaceless>
```

New file `Partials/LogoutFields.html`:
```
<headless:form.registerField name="logintype" value="logout" />
<headless:form.registerField name="pid" value="{storagePid}"/>
<f:spaceless>
    <f:format.raw>
        [
        <f:format.json value="{
            type: 'hidden',
            name: 'pid',
            value: '{storagePid}'
        }"
        />,
        <f:format.json value="{
            type: 'hidden',
            name: 'logintype',
            value: 'logout'
        }"
        />,
        <f:format.json value="{
            type: 'submit',
            name: 'submit',
            value: '{f:translate(key:\'logout\', extensionName:\'felogin\')}'
            }"
        />
        ]
    </f:format.raw>
</f:spaceless>
```

Modify file `Partials/LoginFields.html` (this adds the perma-login option):
```
[...]
        <f:format.json value="{
            type: 'password',
            label: '{f:translate(key:\'input.password\', extensionName:\'headless\')}',
            name: 'pass',
            validate: {
                required: 1,
                password: 1
            },
            options: {
                attr: {
                    placeholder: '{f:translate(key:\'input.password.placeholder\', extensionName:\'headless\')}'
                }
            }
        }"
        />,
// NEW CODE START
        <f:if condition="{permaloginStatus} > -1">
            <f:if condition="{permaloginStatus} == 1">
                <f:then>
                    <f:format.json value="{
                        type: 'hidden',
                        name: 'permalogin',
                        value: '1'
                    }"
                    />,
		</f:then>
		<f:else>
                    <f:format.json value="{
                        type: 'hidden',
                        name: 'permalogin',
                        value: '0'
                    }"
                    />,
		</f:else>
	    </f:if>
        </f:if>
// NEW CODE END
        <f:format.json value="{
            type: 'hidden',
            name: 'pid',
            value: '{storagePid}'
        }"
        />,
[...]
```

After these changes, I'd say this is ready to go.

**Comment by Moongazer** [comment]
Another point I've to mention: if the frontend trys to open a private page, the error-handler responds with a HTML page status 403 (Page Not Found - The page did not exist or was inaccessible.) instead of a JSON error.

I guess this a general task like discussed in #9, how we can handle errors with headless right?

**Comment by lukaszuznanski** [comment]
Hi @Moongazer 
thanks! I will add those changes to PR.

About CORS, you should set correct headers in webserver configuration

**Comment by MichaelNussbaumerGOWEST** [comment]
Any info about this feature? We would need it for a customer website and nothing happend here for quite a while.

**Comment by lukaszuznanski** [comment]
Hi,

@MichaelNussbaumerGOWEST I would like to push this topic further in next week. Requires some polishing and fine tuning.

**Comment by MichaelNussbaumerGOWEST** [comment]
@lukaszuznanski thank you for the quick reply, much needed feature :)

**Review by tmotyl — APPROVED** [review]

**Pull request merged**
