### PR TITLE
[TASK] Prevent conflicts with fluid_styled_content and bootstrap_package

### PR DESCRIPTION
**Pull request by schloram**
When `EXT:fluid_styled_content` or `EXT:bootstrap_package` is installed and included the JSON output of `EXT:headless` is broken. To prevent this I added these two conflicting extensions to "conflicts" in `ext_emconf.php` and `composer.json`.

Additionally to make sure that nothing ever will affect the `tt_content.*` TypoScript I cleared it before using it.

best,
R

### CODE REVIEW

**Comment by lukaszuznanski** [comment]
Nice! Maybe we should also clear other 'libs' such as 'lib.appearance' which we define in typoscript, to make sure that nothing what is included before `headless` typoscript, will break output?

**Comment by schloram** [comment]
> Nice! Maybe we should also clear other 'libs' such as 'lib.appearance' which we define in typoscript, to make sure that nothing what is included before `headless` typoscript, will break output?

Good idea. I'm on it. ;)

**Comment by schloram** [comment]
Done. Please have a look if this is what you had in mind.

**Comment by lukaszuznanski** [comment]
Yea, that's exactly what I meant. Thanks. Works for me, +1.

**Comment by tmotyl** [comment]
Hmm, Cant we make this extension compatible in away that you can have one tree using FSC and other using headless (meaning no global condlict)?

**Comment by schloram** [comment]
In my eyes this doesn't make much sense since headless and fsc are two different extensions with totally different ways of rendering content elements in the frontend. Both just use the pre-defined content elements of `EXT:frontend`. 
I think it's inevitable to mark fsc as conflicting extension (and therefore make sure it's not installed) because it would always break the expected JSON output.

@lukaszuznanski Correct me if I'm wrong. :)

**Comment by schloram** [comment]
@tmotyl I've deleted the conflicting extensions. Since we clear all libs and `tt_content.*` objects before using it we don't get any trouble. Even if the user includes the FCE TypoScript together with the headless TypoScript (no one should do that, though) the JSON is not breaking.

**Comment by tmotyl** [comment]
Thanks, will take a look

**Comment by schloram** [comment]
@tmotyl Sorry for bothering you. Any news on this? :)

**Comment by tmotyl** [comment]
I'm wondering why do we need to clear typoscript objects.
Is there a usecase for including both typoscripts in one tree / site (TS from headless and TS from fluid_styled_content) ?

**Comment by schloram** [comment]
@tmotyl It's just for additional safety that no extension ever interferes with the objects defined in `EXT:headless` (bootstrap_package for instance does this as well). 
Because there are more ways to include TypoScript than as "Static Template" through the backend (Template Module).

E.g:
`EXT:frontend` defines the `tt_content.default` object in `ext_localconf.php` with `\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addTypoScriptSetup`.

So if any other extension uses this kind of TypoScript import (or the `ext_typoscript_setup.typoscript` file) and uses the `tt_content.*` or `lib.*` objects the headless extension uses, this could break the json output.

In these cases it doesn't matter if the user takes care if the TypoScript is included or not. It is enough that the extension is installed/activated to mess with the headless `tt_content.*`/`lib.*` objects.

Its just for error minimization. :)

**Comment by schloram** [comment]
@tmotyl If you don't like it just tell me. It's alright. :) But this PR also contains a bugfix that is important. (see: Configuration/TypoScript/ContentElement/MenuPages.typoscript)

**Comment by schloram** [comment]
@tmotyl Just wanted to ask what's you decision on that issue.

**Comment by schloram** [comment]
As discussed on the video call I'll close this for now. I'll open another one if this becomes an issue again.

**Pull request closed without merging**
